### ISSUE TITLE
Openworld Checklist

### ISSUE THREAD

**Issue by bruhmogus** [The-Arcadis-Team/arc-station-14#70]
- [x] Syndicate job uniforms
- [x] #97 
- [ ] US cargo shuttle
- [ ] Syndicate cargo shuttle
- [x] #104
- [ ] #98
- [x] #99
- [x] #100
- [x] #85 
- [x] #101
- [x] #102
- [x] #103

**Comment by TheDoctor1977** [comment]
> US cargo shuttle

will map this some time today

**Comment by Guloveos** [comment]
Gonna start working on syndicate uniforms o7

**Comment by TheDoctor1977** [comment]
> Computers for syndicate ita and merc shuttle

what does this mean

**Comment by bruhmogus** [comment]
> > Computers for syndicate ita and merc shuttle
> 
> what does this mean

i meant STATIONS, so less nt looking cargo request for example
