### ISSUE TITLE
Upstream change checklist

### ISSUE THREAD

**Issue by Guloveos** [The-Arcadis-Team/arc-station-14#89]
## Description
This is the check list for the fork port

- [ ]  The NTPD as a whole (clothing, ghost roles, radio channel, access, doors, the alert level, ntpd pistol, armor, vendor, _uplink_)

- [ ] Urban solutions (Clothing (envirosuit and envirokit), Ghost roles, radio channel, access, airlock, docking airlock, META)

- [x]  The meat hunk and its ghost role as well as the void husks

- [ ]  amulet, gauntlets, abyss blocker, custom flesh blocker, ITA access, airlocks, and high sec door

- [ ] #105

- [x]  Admin references

- [x]  Toweg Clothing, items and prototype, The detective clothing, items and prototype

- [x]  The captain and HoS plushys

**Comment by Erisfiregamer1** [comment]
If I stop posting daily updates on this assume I had a heart attack and died, or just got fatally burnt out from this.

**Comment by Erisfiregamer1** [comment]
Update 2: Wyatt and Dusty's plushies have been ported with some tweaks to satisfy my eternal horror. Working on porting the logos now.

**Comment by a-person5660** [comment]
should admin invisiwalls be on this list?

**Comment by Erisfiregamer1** [comment]
Update 3: Hoo boy this is going to be a long night. Ported a lot of stuff, including blacklight. Italicized in unchecked box means that section was ported.

I AM NOT CHANGING THE FLOOR TILES!!!

**Comment by a-person5660** [comment]
> I AM NOT CHANGING THE FLOOR TILES!!!

as in not changing them to EE or not changing them from EE?

**Comment by Erisfiregamer1** [comment]
> > I AM NOT CHANGING THE FLOOR TILES!!!
> 
> as in not changing them to EE or not changing them from EE?

I am not changing them from EE, if you hate them THAT badly go PR the fucking change yourself. I am doing nothing but porting TO EE.

**Comment by a-person5660** [comment]
i prefer EE anyway.

**Comment by Erisfiregamer1** [comment]
Update 4: oops I forgont

A lot of this will be on hold as we work on NEW content for the fork, including tweaks. Port it yourself if you want it from wizden-old.

**Comment by TheDoctor1977** [comment]
closing this as the vision for the server (development-wise) has drifted wildly since it was created
